Create ESP

diff --git a/part2/stages/Functions/install-main b/part2/stages/Functions/install-main
--- a/part2/stages/Functions/install-main
+++ b/part2/stages/Functions/install-main
@@ -388,7 +388,11 @@ commit_dom0()
 
     do_cmd mkdir -p ${DOM0_MOUNT}/storage/disks || return 1
 
-    install_bootloader_from_dom0fs || return 1
+    if [ -d /sys/firmware/efi/efivars ]; then
+        setup_efi || return 1
+    else
+        install_bootloader_from_dom0fs || return 1
+    fi
 
     mixedgauge "Taking ownership of TPM" 50
 
@@ -528,6 +532,72 @@ install_bootloader_from_dom0fs()
         echo "Error installing the bootloader">&2
         return 1
     }
+    return 0
+}
+
+setup_efi()
+{
+    local DISK_DEV="/dev/${TARGET_DISK}"
+    local ESP=$(sfdisk -l $1 2>/dev/null | grep "EFI System" | awk '{print $1}')
+    if [ -z ${ESP} ]; then
+        echo "No EFI System Partition on disk ${DISK_DEV}"
+        return 1
+    fi
+
+    do_mount ${ESP} ${ESP_MOUNT} 2> /dev/null
+    if [ "$?" != "0" ]; then
+        echo "Couldn't mount ${ESP}, already mounted?"
+        return 1
+    fi
+
+    do_cmd mkdir -p ${ESP_MOUNT}/EFI/openxt
+    do_cmd cp -f ${DOM0_MOUNT}/boot/xen.efi \
+          ${DOM0_MOUNT}/boot/shimx64.efi \
+          ${DOM0_MOUNT}/boot/bzImage \
+          ${DOM0_MOUNT}/boot/initramfs.gz \
+          ${DOM0_MOUNT}/boot/microcode_intel.bin \
+          ${DOM0_MOUNT}/etc/xen/xenrefpolicy/policy/policy.24 \
+          ${DOM0_MOUNT}/usr/share/xenclient/bootloader/openxt.cfg \
+          ${ESP_MOUNT}/EFI/openxt
+
+    if [ "$?" != "0" ]; then
+        echo "Failed to copy files to ESP"
+        do_cmd umount ${ESP_MOUNT}
+        return 1
+    fi
+
+    do_cmd umount ${ESP_MOUNT}
+
+    do_cmd efibootmgr -w -L "OpenXT" -l "\EFI\openxt\shimx64.efi" -c -d ${DISK_DEV} --part 1
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry"
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT (safe graphics)" -l "\EFI\openxt\shimx64.efi" -C -d ${DISK_DEV} --part 1 -u "openxt-support-safe-graphics"
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry"
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT (AMT)" -l "\EFI\openxt\shimx64.efi" -C -d ${DISK_DEV} --part 1 -u "openxt-support-amt"
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry"
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT (console)" -l "\EFI\openxt\shimx64.efi" -C -d ${DISK_DEV} --part 1 -u "openxt-support-console"
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry"
+        return 1
+    fi
+
+    do_cmd efibootmgr -w -L "OpenXT (console AMT)" -l "\EFI\openxt\shimx64.efi" -C -d ${DISK_DEV} --part 1 -u "openxt-support-console-amt"
+    if [ "$?" != "0" ]; then
+        echo "Couldn't create EFI boot entry"
+        return 1
+    fi
+
     return 0
 }
 
